### PR TITLE
Improve SHA256 equality checks

### PR DESCRIPTION
**Pull request by Apelsinka223**
Hi! I suggest to add `equal?/2` callback in sha_256 type, so when you do not change this field in changeset ecto would skip it in update (for now ecto update field all the time)

### CODE REVIEW

**Comment by jwaldrip** [comment]
@danielberkompas would love to see this merged as well.

**Comment by danielberkompas** [comment]
This has been added in version 1.1.1!

**Comment by danielberkompas** [comment]
I added a version of this today but it didn't do any hashing. It just uses basic string comparison. Is there any documentation on what values Ecto will pass to the `equal?` function?

**Comment by Apelsinka223** [comment]
Hi @danielberkompas ! 
If I understood your question correctly, Ecto passes as first argument the origin not updated version of the field value, and as second argument - the new updated version of the value. So if any of these versions of value is not hashed (basically the second - new version), this code will hash it and compare both hashed values. 
I recognize hashed value with `String.valid?` function, which should return false. Maybe in your code, the unhashed value doesn't pass this check, and that's why it turning out to basic string comparison, because it recognized as hashed. Can you show with which values you tested this code?

**Comment by danielberkompas** [comment]
It's late in coming, but thanks @Apelsinka223! :star:

**Pull request merged**
